---
- hosts: localhost
  connection: localhost
  gather_facts: no
  tasks: 
    - name: Create Network, Subnet, Router
      import_role:
        name: openstack_networking

    - name: Create Keypair, Server
      import_role:
        name: openstack_compute

    - name: Get API Token
      import_role:
        name: api_common

    - name: Create Firewall
      import_role:
        name: api_firewall

    - name: Get Server Password
      import_role:
        name: api_compute

- hosts: winservers
  gather_facts: no
  become: no
  tasks:
    - name: Windows Default Settings
      import_role:
        name: windows

    - name: 'Zabbix Setup'
      import_role:
        name: win_zabbix