---
- hosts: localhost
  connection: localhost
  gather_facts: no
  tasks: 
    - name: Create Network, Subnet, Router
      import_role:
        name: openstack_networking

    - name: Create Keypair
      import_role:
        name: openstack_compute

    - name: Get API Token
      import_role:
        name: api_common

    - name: Create Firewall
      import_role:
        name: api_firewall
