# Keypair
# import_key: "yes"|"no"
import_key: "no"
public_key_name: os_ansible_key
public_key_file: os_ansible_key.pub
private_key_file: os_ansible_key.pem
output_dir: files
# users_public_key: /home/user/.ssh/id_rsa.pub
# users_public_key: /home/user/.ssh/id_rsa.pub

# server.yml
server_name: "os_default_server1"
server_flavor: "T3-1"
key_pair: os_ansible_key.pub
volume_name: "os_default_volume1"
volume_image: "CentOS 7.8 64bit (English) 01"
volume_size: 40
