---
- name: 'Get my public ip address'
  ipify_facts:
    timeout: 30
  when: use_my_ip  == "yes"

- name: 'Create security groups'
  openstack.cloud.security_group:
    cloud: "{{ target_cloud | default(omit) }}"
    state: present
    name: "{{ item }}"
  with_items: "{{ security_groups }}"

- name: 'Create security group rules'
  openstack.cloud.security_group_rule:
    security_group: "{{ item.security_group }}"
    protocol: "{{ item.protocol }}"
    port_range_min: "{{ item.port_range_min | default(omit) }}"
    port_range_max: "{{ item.port_range_max | default(omit) }}"
    remote_ip_prefix: "{{ allow_ip | default(item.remote_ip_prefix) }}"
    cloud: "{{ target_cloud | default(omit) }}"
    state: present
  with_items: "{{ security_group_rules }}"