---
- name: 'Create subnet'
  openstack.cloud.subnet:
    state: present
    network_name: "{{ network_name }}"
    name: "{{ subnet_name }}"
    cidr: "{{ cidr }}"
    gateway_ip: "{{ gateway_ip | default(cidr | ipaddr('broadcast') | ipmath(-1)) }}"
    dns_nameservers: "{{ dns }}"
    enable_dhcp: "{{ enable_dhcp }}"
    allocation_pool_start: "{{ dhcp_pool_start | default(cidr | ipmath(+1)) }}" 
    allocation_pool_end: "{{ dhcp_pool_end | default(cidr | ipaddr('broadcast') | ipmath(-2)) }}"
